services:
  - type: web
    name: csolflask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_USER
        value: fvckyopue
      - key: DB_PASSWORD
        value: d5kQa7pzXbrHUg8A
      - key: DB_HOST
        value: mysql2.sqlpub.com
      - key: DB_PORT
        value: 3307
      - key: DB_NAME
        value: csolkz
      - key: PYTHON_VERSION
        value: 3.9.18 